# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.trade.com:
  peer0.exporterorg.trade.com:
  peer0.importerorg.trade.com:
  peer0.carrierorg.trade.com:
  peer0.regulatororg.trade.com:

networks:
  trade:
services:
  exporter-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-exporterorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exporterorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/87f798b6dd56da7c352b129fdb1488fa1f433e27238694048bd8c595389af70c_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.exporterorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/87f798b6dd56da7c352b129fdb1488fa1f433e27238694048bd8c595389af70c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/exporterorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerExporterOrg
    networks:
      - trade

  importer-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.importerorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/38a8e087b0087d847112ba7eee8a3799b31d3bd6d3bc6289fabdab7337962150_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.importerorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/38a8e087b0087d847112ba7eee8a3799b31d3bd6d3bc6289fabdab7337962150_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importerorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerImporterOrg
    networks:
      - trade
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.importerorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ImporterOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/importerorg.trade.com/users/Admin@importerorg.trade.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
    networks:
        - trade
 

  carrier-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-carrierorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.carrierorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0a0793414375a99971a86294683d1bfb9a7c2a6f75b2795764f56bc024188668_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.carrierorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0a0793414375a99971a86294683d1bfb9a7c2a6f75b2795764f56bc024188668_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/carrierorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCarrierOrg
    networks:
      - trade

  regulator-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-regulatororg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.regulatororg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/dd4b14fd73499add18981318c900a17c5e9fa8c500f2bdb0e98599516750c0b8_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.regulatororg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/dd4b14fd73499add18981318c900a17c5e9fa8c500f2bdb0e98599516750c0b8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/regulatororg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerRegulatorOrg
    networks:
      - trade

  orderer.trade.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.trade.com
    container_name: orderer.trade.com
    networks:
      - trade

  peer0.exporterorg.trade.com:
    container_name: peer0.exporterorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporterorg.trade.com
    networks:
      - trade

  peer0.importerorg.trade.com:
    container_name: peer0.importerorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.importerorg.trade.com
    networks:
      - trade

  peer0.carrierorg.trade.com:
    container_name: peer0.carrierorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.carrierorg.trade.com
    networks:
      - trade

  peer0.regulatororg.trade.com:
    container_name: peer0.regulatororg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.regulatororg.trade.com
    networks:
      - trade
