NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.carrierorg.trade.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.carrierorg.trade.com-cert.pem
    OrganizationalUnitIdentifier: peer
