NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.regulatororg.trade.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.regulatororg.trade.com-cert.pem
    OrganizationalUnitIdentifier: peer
